### ISSUE TITLE
Can this tool only be used in NEU?

### ISSUE THREAD

**Issue by zhixuanli** [j178/ipgw#1]
Can this tool only be used in NEU?
After viewed the ipgw.py, I'm confused whether this useful tool can be use in another university?

Thank you!

**Comment by j178** [comment]
Thank you for your appreciation 😄 
This tool is nothing but a simple scirpt that simulates requests, adding some not so useful functions.
In theory, it is easy to port this script for other schools. But network conditions in each school differ a lot, it is difficult to adapt.
If anyone wants to make this scirpt more general, we should refactor the code to make it possible to write extension for it, to make it usable in other universities.

**Comment by zhixuanli** [comment]
Thank you so much!!!
